
networks:
  microservices-net:
    driver: overlay

volumes:
  user-data:
  task-data:

secrets:
  db_user:
    external: true  # Говорим Compose, что секрет уже создан в Swarm извне
  db_password:
    external: true
  jwt_secret:
    external: true

services:
  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    image: eureka-server:latest
    ports:
      - "8761:8761"
    networks:
      - microservices-net
    environment:
      - EUREKA_INSTANCE_HOSTNAME=eureka-server
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  # ==================== БАЗЫ ДАННЫХ ====================
  postgres-user:
    image: postgres:15.8
    secrets:
      - db_user
      - db_password
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres        # ← ОБЯЗАТЕЛЬНО!
      POSTGRES_PASSWORD: postgres
      #POSTGRES_USER_FILE: /run/secrets/db_user
      #POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - "5433:5432"
    volumes:
      - user-data:/var/lib/postgresql/data
    networks:
      - microservices-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  postgres-task:
    image: postgres:15.8
    secrets:
      - db_user
      - db_password
    environment:
      POSTGRES_DB: task_db
      POSTGRES_USER: postgres        # ← ОБЯЗАТЕЛЬНО!
      POSTGRES_PASSWORD: postgres
      #POSTGRES_USER_FILE: /run/secrets/db_user
      #POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - "5434:5432"
    volumes:
      - task-data:/var/lib/postgresql/data
    networks:
      - microservices-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  # ==================== МИКРОСЕРВИСЫ ====================
  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile  # обрати внимание на заглавную D
    image: user-service:latest
    secrets:
      - db_user
      - db_password
      - jwt_secret
    ports:
      - "8081:8081"
    depends_on:
      - postgres-user
      - eureka-server
    volumes:
      - ./user-service/src:/app/user-service/src
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-user:5432/user_db
      SPRING_DATASOURCE_USERNAME_FILE: /run/secrets/db_user
      SPRING_DATASOURCE_PASSWORD_FILE: /run/secrets/db_password
      JWT_SECRET_FILE: /run/secrets/jwt_secret
    networks:
      - microservices-net
    deploy:
      replicas: 1  # пока 1, чтобы легче отлаживать
      restart_policy:
        condition: on-failure

  task-service:
    build:
      context: .
      dockerfile: task-service/Dockerfile
    image: task-service:latest
    secrets:
      - db_user
      - db_password
      - jwt_secret
    ports:
      - "8082:8082"
    depends_on:
      - postgres-task
      - eureka-server
    volumes:
      - ./task-service/src:/app/task-service/src
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-task:5432/task_db
      SPRING_DATASOURCE_USERNAME_FILE: /run/secrets/db_user
      SPRING_DATASOURCE_PASSWORD_FILE: /run/secrets/db_password
      JWT_SECRET_FILE: /run/secrets/jwt_secret
      USER_SERVICE_URL: http://user-service:8081
    networks:
      - microservices-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    image: api-gateway:latest
    secrets:
      - jwt_secret
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - task-service
      - eureka-server
    volumes:
      - ./api-gateway/src:/app/api-gateway/src
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      USER_SERVICE_URL: http://user-service:8081
      TASK_SERVICE_URL: http://task-service:8082
    networks:
      - microservices-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend:latest
    ports:
      - "3000:80"
    networks:
      - microservices-net
    depends_on:
      - api-gateway
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  admin-server:
    build:
      context: .
      dockerfile: admin-server/Dockerfile
    image: admin-server:latest
    ports:
      - "9090:9090"  # Порт для доступа к UI
    depends_on:
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
      SPRING_BOOT_ADMIN_DISCOVERY_ENABLED: "true"
    networks:
      - microservices-net
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure