server:
  port: 8082

spring:
  application:
    name: task-service
  config:
    import:
      - optional:file:/common-config/application-devtools.yml
      - optional:file:/common-config/application-actuator.yaml



  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true


eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/  # ← АДРЕС EUREKA
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name}:${random.value}
    hostname: ${spring.application.name}
    prefer-ip-address: false  # Регистрироваться по IP, а не по hostname
    lease-renewal-interval-in-seconds: 30  # Частота отправки heartbeats
    lease-expiration-duration-in-seconds: 90  # Через сколько удалить, если нет heartbeats
logging:
  level:
    com.todo: DEBUG